# Classify Hymenoptera species

In [1]:
##############################################################################
#                                                                            #
#                ▄▄████████████▄ ▐                                           #
#             ▄███▀▀▀▀▀▀▀████████▐                                           #
#         ▄▀▀▀▄▄▄▄███████▄▄▄▄▀▀▀█▐                                           #
#      ▄▛ ▟█████████████████████▄▐                                           #
#    ▄█▛ ▟█         ▀▚   █████   ▐                                           #
#   ███ ██▌   ▄▄▄▖   ▐  ▐████▌   ▐    ████████ ████████  ▟████▙   ██     ██  #
#  ████ ██▌   ███▛   ▐  ▐████▌   ▐       ██    ██       ▟█▛  ▜█▙  ██     ██  #
#  ████ ▀█           ▞  █████    ▐       ██    ███████  ██        █████████  #
#  █████ █   ▄▄▄▄▄▄▄▞   ▜██▛    ▐▐       ██    ██       ▜█▙  ▟█▛  ██     ██  #
#   █████    ██████            ▐█▐       ██    ████████  ▜████▛   ██     ██  #
#    █████  ███████▙          ▟██▐                                           #
#     ▀████▙▀▀▀█████████████▀▀▀▄▄▐                                           #
#       ▀██████▄▄▄▄▀▀▀▀▀▄▄▄▄█████▐                                           #
#          ▀███████████████████▀ ▐                                           #
#             ▀▀███████████▀▀    ▐                                           #
#                                                                            #
##############################################################################

In [1]:
# import the necessary packages
import numpy as np
import argparse
import time
import cv2
import os
import pytorch

ModuleNotFoundError: No module named 'pytorch'

# Constants

In [12]:
DATA_PATH = "./dataset/Hymenoptera.v2i.yolov5pytorch"
MODEL_PATH = "./model"

# Load dataset

In [42]:
# import custom dataset
labels = open(os.path.join(DATA_PATH, "obj.names")).read().splitlines()
np.random.seed(45)
boxColors = np.random.randint(0, 255, size=(len(labels), 3), dtype="uint8")
print(labels)
print(boxColors)

['Abeille', 'Guepe', 'Frelon Européen', 'Frelon Oriental', 'Frelon Asiatique']
[[203 219  47]
 [253 158  25]
 [246  77 131]
 [246 174 140]
 [124  23 230]]


# Load model

In [57]:
net = cv2.dnn.readNetFromDarknet(os.path.join(MODEL_PATH, "cfg", "yolov2-voc.cfg"), os.path.join(MODEL_PATH,"yolov2-voc.weights"))

In [63]:
layer_names = net.getLayerNames()
output_layers = [layer_names[i-1] for i in net.getUnconnectedOutLayers()]

# Retrain the model with our data

# Testing with a new image

In [55]:
# load the image from disk
image = cv2.imread('./image/image_1.jpeg')
# create blob from image
blob = cv2.dnn.blobFromImage(image=image, scalefactor=0.01, size=(224, 224), mean=(104, 117, 123))

In [69]:
# set the input blob for the neural network
net.setInput(blob)
# forward pass image blog through the model
outputs = net.forward()


In [ ]:
outputs

In [71]:
final_outputs = outputs[0]
# make all the outputs 1D
final_outputs = final_outputs.reshape(25)
# get the class label
label_id = np.argmax(final_outputs)
# convert the output scores to softmax probabilities
probs = np.exp(final_outputs) / np.sum(np.exp(final_outputs))
# get the final highest probability
final_prob = np.max(probs) * 100.
# map the max confidence to the class label names
out_name = labels[label_id]
out_text = f"{out_name}, {final_prob:.3f}"
print(out_text)

Frelon Oriental, 4.472


## Metrics

In [ ]:
import sklearn.metrics as metrics

In [ ]:
# y_true = ["cat", "ant", "cat", "cat", "ant", "bird"]
# y_pred = ["ant", "ant", "cat", "cat", "ant", "cat"]
metrics.confusion_matrix(y_true, y_pred, labels=labels)